name: padel_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  uuid:
  get_storage:
  connectivity_plus:
  dio:
  logger:
  flutter_svg:
  pin_code_fields:
  flutter_rating_bar:
  easy_date_timeline:
  intl:
  flutter_map:
  latlong2:
  google_nav_bar:
  flutter_slidable:
  dropdown_search:
  image_picker:
  cached_network_image:
  razorpay_flutter:
  flutter_local_notifications:
  firebase_messaging:
  timezone:
  permission_handler:
  firebase_core:
  flutter_dash:
  shimmer:
  firebase_crashlytics:
  share_plus:
  flutter_zoom_drawer:
  loading_animation_widget:




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie_files/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400

    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato/Lato-Light.ttf
          weight: 500
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700